server:
  port: 9001

spring:
  data:
    mongodb:
      uri: mongodb+srv://dbuser:dbpassword@primary.ofp4b.mongodb.net/primarydb?retryWrites=true&w=majority

  application:
    name: APPLICATION-SERVER